version: "3.9"

services:
  mysql:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${MYSQL_DB}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - go-network

  go-multi-chat-api:
    build:
      context: .
    image: go-multi-chat-api
    restart: on-failure
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - go-network
    environment:
      # Server Configuration
      - SERVER_PORT=${SERVER_PORT:-8080}
      
      # Database Configuration
      - DB_HOST=${DB_HOST:-mysql}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_SSLMODE=${DB_SSLMODE:-disable}
      
      # Database Connection Pool Configuration
      - DB_MAX_IDLE_CONNS=${DB_MAX_IDLE_CONNS:-10}
      - DB_MAX_OPEN_CONNS=${DB_MAX_OPEN_CONNS:-50}
      - DB_CONN_MAX_LIFETIME=${DB_CONN_MAX_LIFETIME:-300}
      
      # JWT Configuration
      - JWT_ACCESS_SECRET_KEY=${JWT_ACCESS_SECRET_KEY}
      - JWT_ACCESS_TIME_MINUTE=${JWT_ACCESS_TIME_MINUTE:-15}
      - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
      - JWT_REFRESH_TIME_HOUR=${JWT_REFRESH_TIME_HOUR:-168}
      - JWT_ISSUER=${JWT_ISSUER}
      
      # Initial User Configuration
      - START_USER_EMAIL=${START_USER_EMAIL:-anandhans8@gmail.com}
      - START_USER_PW=${START_USER_PW:-qwerty123}

      # LDAP Configuration
      - LDAP_ENABLED=false                   # Set to true to enable LDAP authentication
      - LDAP_URL=ldap.example.com:389        # LDAP server URL with port
      - LDAP_BIND_DN=cn=admin,dc=example,dc=com  # Service account DN for initial bind
      - LDAP_BIND_PASSWORD=admin_password    # Service account password
      - LDAP_BASE_DN=dc=example,dc=com       # Base DN for user search
      - LDAP_USER_FILTER=(uid=%s)            # Filter to search for users, %s will be replaced with username
      - LDAP_TLS_ENABLED=false               # Set to true to use TLS for LDAP connection
      - LDAP_ATTRIBUTES=uid,mail,givenName,sn # Comma-separated list of attributes to retrieve

      # Azure AD Configuration
      - AZURE_AD_ENABLED=false               # Set to true to enable Azure AD authentication
      - AZURE_AD_TENANT_ID=your-tenant-id    # Azure AD Tenant ID
      - AZURE_AD_CLIENT_ID=your-client-id    # Azure AD Client ID
      - AZURE_AD_CLIENT_SECRET=your-client-secret # Azure AD Client Secret
      - AZURE_AD_REDIRECT_URI=http://localhost:8080/auth/callback # Redirect URI after
      - AZURE_AD_SCOPE=openid,profile,email





volumes:
  mysqldata:

networks:
  go-network:
    driver: bridge
